# Generated by Django 3.1.7 on 2021-04-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="server",
            name="dogeboard_id",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="server",
            name="server_id",
            field=models.CharField(max_length=60),
        ),
    ]
