# Generated by Django 3.1.7 on 2021-04-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servers", "0002_auto_20210407_2053"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="dogeboard_emoji",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
