# Generated by Django 3.1.7 on 2021-04-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servers", "0003_server_dogeboard_emoji"),
    ]

    operations = [
        migrations.AlterField(
            model_name="server",
            name="server_id",
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
