# Generated by Django 3.1.7 on 2021-04-07 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servers", "0004_auto_20210407_2143"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="dogeboard_reactions_required",
            field=models.IntegerField(default=5),
        ),
    ]
