# Generated by Django 3.1.1 on 2020-09-09 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bot_admin",
            field=models.BooleanField(default=False),
        ),
    ]
