# Generated by Django 3.2.5 on 2022-03-11 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_watchlist_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='owners',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='maintainers',
            field=models.ManyToManyField(related_name='maintained_watchlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owned_watchlists', to='users.user'),
            preserve_default=False,
        ),
    ]
