# Generated by Django 3.1.1 on 2020-10-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="discord_id",
            field=models.CharField(max_length=18, null=True),
        ),
    ]
