# Generated by Django 3.1.3 on 2020-12-03 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_discord_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AuthToken",
        ),
    ]
