# Generated by Django 3.1.3 on 2020-11-25 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_auto_20201125_0135"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="discord_discriminator",
            field=models.CharField(default=None, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="discord_id",
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="discord_username",
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
