# Generated by Django 3.1.3 on 2020-11-25 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_auto_20201125_0137"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="discord_avatar",
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="discord_discriminator",
            field=models.CharField(blank=True, default=None, max_length=4),
        ),
        migrations.AlterField(
            model_name="user",
            name="discord_id",
            field=models.BigIntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name="user",
            name="discord_username",
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
