# Generated by Django 3.1.3 on 2020-11-25 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_auto_20201125_0153"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="discord_avatar",
        ),
    ]
