# Generated by Django 3.1.3 on 2020-11-25 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_remove_user_discord_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="discord_avatar",
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
