# Generated by Django 3.1.3 on 2020-11-25 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_user_discord_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(),
        ),
    ]
