# Generated by Django 3.1.3 on 2020-11-30 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_auto_20201125_0211"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="discord_avatar",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="discord_discriminator",
            field=models.CharField(blank=True, default=None, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="discord_id",
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="discord_username",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
