# Generated by Django 3.1.3 on 2020-12-02 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_user_is_bot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="discord_id",
            field=models.BigIntegerField(
                blank=True, default=None, null=True, unique=True
            ),
        ),
    ]
