# Generated by Django 3.1.7 on 2021-04-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Guild",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guild_id", models.BigIntegerField(unique=True)),
                ("dogeboard_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "dogeboard_emoji",
                    models.CharField(blank=True, max_length=60, null=True),
                ),
                ("dogeboard_reactions_required", models.IntegerField(default=5)),
            ],
        ),
    ]
