# Generated by Django 3.2.5 on 2021-07-05 03:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Guild",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guild_id", models.BigIntegerField(unique=True)),
                ("dogeboard_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "dogeboard_emoji",
                    models.CharField(blank=True, max_length=60, null=True),
                ),
                (
                    "dogeboard_reactions_required",
                    models.PositiveIntegerField(
                        default=5,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
            ],
        ),
    ]
