# Generated by Django 3.1.7 on 2021-04-10 20:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guilds", "0002_auto_20210410_2037"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guild",
            name="dogeboard_reactions_required",
            field=models.PositiveIntegerField(
                default=5, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
